# Generated by Django 4.2.6 on 2023-11-21 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='address_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='address_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='zipcode',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
