# Generated by Django 4.2.6 on 2023-11-23 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gt', '0003_account_walking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='walking',
        ),
    ]
