# Generated by Django 4.2.7 on 2023-11-29 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gt', '0006_searchhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='account',
        ),
        migrations.RemoveField(
            model_name='map',
            name='category',
        ),
        migrations.RemoveField(
            model_name='map',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='map',
            name='location_name',
        ),
        migrations.RemoveField(
            model_name='map',
            name='longitude',
        ),
        migrations.AddField(
            model_name='map',
            name='json_data',
            field=models.TextField(null=True, verbose_name='json_data'),
        ),
        migrations.AddField(
            model_name='map',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='場所名'),
        ),
        migrations.AlterField(
            model_name='map',
            name='address',
            field=models.CharField(max_length=200, null=True, verbose_name='住所'),
        ),
    ]
