# Generated by Django 4.2.7 on 2023-12-02 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gt', '0008_mapbike_mapcar_delete_map'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spot',
            name='business_hours',
        ),
        migrations.RemoveField(
            model_name='spot',
            name='category',
        ),
        migrations.RemoveField(
            model_name='spot',
            name='contact_info',
        ),
        migrations.RemoveField(
            model_name='spot',
            name='fee_info',
        ),
        migrations.RemoveField(
            model_name='spot',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='spot',
            name='longitude',
        ),
        migrations.AddField(
            model_name='spot',
            name='json_data',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='spot',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gt.account'),
        ),
        migrations.AlterField(
            model_name='spot',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='spot',
            name='spot_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='spot',
            name='spot_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
