# Generated by Django 4.2.6 on 2023-12-02 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gt', '0009_account_activation_code_account_email_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='email_confirmed',
        ),
    ]
