# Generated by Django 4.2.6 on 2023-12-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gt', '0009_remove_spot_business_hours_remove_spot_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='email_verified',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
