# Generated by Django 4.2.6 on 2023-12-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gt', '0010_account_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='end_location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='目的地'),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='start_location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='出発地'),
        ),
    ]
