# Generated by Django 4.2.7 on 2023-12-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gt', '0013_remove_searchhistory_search_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
