# Generated by Django 4.2.7 on 2024-01-30 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gt', '0014_account_latitude_account_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', '男'), ('F', '女'), ('O', 'その他')], max_length=100),
        ),
    ]
