# Generated by Django 4.2.7 on 2024-01-15 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gt', '0014_account_latitude_account_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='end_spot_label',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='目的地スポット'),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='start_spot_label',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='出発地スポット'),
        ),
    ]
